# @package _global_
defaults:
  - /benchmark/nav/objectnav/objectnav_hm3d
  - _self_

habitat:
  dataset:
    split: val
    data_path: data/datasets/objectnav/hm3d/v2/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets
  simulator:
    habitat_sim_v0:
      gpu_device_id: 0
